name: Python application
on: workflow_dispatch
jobs:
  build:
    runs-on: label-1
    steps:
    - name: Chekout
      uses: actions/checkout@v6.0.2
    - name: VenvAct
      run: python3 -m venv venv
    - name: requirements
      run: venv/bin/pip install -r requirements.txt
    - name: Secrets
      run: touch tgToken.py &&\tgToken.py >> ${{secrets.tgToken}} &&\tgToken.py >> ${{secrets.chatId}} &&\
    - name: Start
      run: python3 app.py
