name: Python application
on: workflow_dispatch
jobs:
  build:
    runs-on: label-1
    steps: Chekout
      uses: actions/checkout@v6.0.2
    steps: VenvAct
      run: python3 -m venv venv
    steps: requirements
      run: venv/bin/pip install -r requirements.txt
    steps: Secrets
      run: touch tgToken.py &&\tgToken.py >> ${{secrets.tgToken}} &&\tgToken.py >> ${{secrets.chatId}} &&\
    steps: Start
      run: python3 app.py
