name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    jobs:
      apppy:
        runs-on: self-hosted
        steps:
        - name: Chekout
          uses: actions/checkout@v6.0.2
        - name: VenvAct
          run: python3 -m venv venv
        - name: requirements
          run: venv/bin/pip install -r requirements.txt
        - name: Secrets
          run: touch tgToken.py && echo ${{secrets.TGTOKEN}} >> tgToken.py && echo "\n" >> tgToken.py && echo ${{secrets.CHATID}} >> tgToken.py
        - name: Start
          run: python3 app.py
